name: pastel_habit_garden
description: "Habit tracker with cute plants 🌱✨"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3       # State management (BLoC)
  equatable: ^2.0.5          # Easy object comparison
  get_it: ^7.6.4             # Dependency injection
  lottie: ^2.7.0             # Cute animations
  shared_preferences: ^2.2.2  # Local storage
  uuid: ^3.0.7               # Unique IDs
  google_fonts: ^4.0.4       # Stylish fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4          # BLoC testing
  mocktail: ^0.3.0           # Mocking for tests

flutter:
  uses-material-design: true
  assets:
    - assets/animations/      # Sabai animation files
    - assets/images/          # Plant images